### ISSUE TITLE
How to make a trait object from CArc?

### ISSUE THREAD

**Issue by kenfred** [h33p/cglue#13]
I'm having trouble turning a `CArc<MyStruct>` into a trait object `MyTraitArcBox<'static>`.

I have tried something like below. Assume that `MyTrait` has been decorated with `#[cglue_trait]` and I have an impl of `MyTrait` for `MyStruct`.
```rust
let foo = CArc::from(MyStruct{});
let obj = trait_obj!(foo as MyTrait);
```

This expands to:
```rust
::cglue::trait_group::Opaquable::into_opaque({
    use ::cglue::from2::From2;
    MyTraitBase::from2(foo)
})
```

I get the error:
```shell
    |    let obj = trait_obj!(foo as MyTrait);
    |              -----------^^^------------------------------------
    |              |          |
    |              |          the trait `From<cglue::arc::CArc<MyStruct>>` is not implemented for `CGlueTraitObj<'_, _, MyTraitVtbl<'_, CGlueObjContainer<_, _, PhantomData<MyTraitRetTmpPhantom<_>>>>, _, PhantomData<MyTraitRetTmpPhantom<_>>>`
    |        
```
I can tell from the error that the cast I'm doing is converting to a `CGlueTraitObj` that has no context, which I believe is incorrect for an Arc-based trait object.

The only example I can find with pointers instead of simple references is this this plugin example:
```rust
extern "C" fn create_plugin(lib: &CArc<cglue::trait_group::c_void>) -> PluginInnerArcBox<'static> {
    trait_obj!((KvRoot::default(), lib.clone()) as PluginInner)
}
```
If I understand correctly, this makes the `KvRoot` the instance and the `CArc<Library>` (now an opaque `CArc<cglue::trait_group::c_void>`) the context of the `CGlueTraitObj`.

This is interesting because it effectively attaches the `KvRoot` instance to the lifetime of the `Library`. Does this `instance` have the same access semantics as an Arc?

I believe what I'm trying to accomplish is that the instance _and_ the context both refer to the underlying CArc. I have tried to cast it to various things I can think of, but no luck. Can someone clear this up for me?

Thanks!

**Comment by h33p** [comment]
This may be a problem on my end for naming things confusingly, but `CArc<T>` is equivalent to `Option<Arc<T>>`, therefore it does not have a `Deref` implementation, which is required for a container to be compatible.

The way to use a C arc, is to use `CArcSome<T>`, which does implement `Deref`.
