### ISSUE TITLE
A few questions about the library

### ISSUE THREAD

**Issue by marioortizmanero** [h33p/cglue#3]
Hi there Auri!

You [left a comment](https://www.reddit.com/r/rust/comments/q2n6b8/plugins_in_rust_diving_into_dynamic_loading/hfmyn6o/) on one of my last posts regarding a plugin system in Rust, where you brought up this crate. I'm closer to releasing a follow-up, so I wanted to ask you a few questions to make sure I'm not misunderstanding anything, if that's ok with you.

Is this technically the same as [`#[abi_stable::sabi_trait]`](https://docs.rs/abi_stable/0.10.3/abi_stable/sabi_trait/index.html)? Not sure if you've ever used it before. This procedural macro in the `stabl_abi` crate basically lets you crate FFI-safe trait objects, which you can even downcast if configured to.

The main difference I can see is that `cglue` allows *trait groups*, which is something that `sabi_trait` doesn't implement. `cglue` seems to be oriented to Rust-to-C and Rust-to-C++, too, in comparison to `abi_stable`, which is meant for Rust-to-Rust and can't even generate C bindings.

Are my assumptions correct? Anything else you'd like me to mention in the post? Thanks!

**Comment by h33p** [comment]
Hey there!

Your understanding is correct. CGlue effectively is a macro that lets you create FFI-safe objects. And the differences are basically that - trait groups seemed to come in very handy for plugins, and the focus for C/C++ interoperability is there to allow bridging Rust with other languages.

There are some additional differences in code generation - CGlue aims to be almost as drop-in as it gets for exposing traits to plugin systems or other languages, which means there is transparent type wrapping going on behind the scenes, and facilities for using associated types.

Other than that, I think that's it. I'm very excited to read your next post!

**Comment by marioortizmanero** [comment]
Thanks a lot. By the way, I think your blog http://blaz.is/ is dead, I was going to link it in my post.

**Comment by h33p** [comment]
Yeah, I happened to have messed up DNS, now it's back up.

**Comment by marioortizmanero** [comment]
Just uploaded it here: https://nullderef.com/blog/plugin-abi-stable/

If there's anything you want to add to your section let me know :) Thanks for the help

**Comment by h33p** [comment]
No problem, it was a pleasure :)
