### ISSUE TITLE
Use of private module from sub-dependency

### ISSUE THREAD

**Issue by emesare** [h33p/cglue#6]
I get these errors when building the crate [memflow](https://github.com/memflow/memflow), however it appears to have nothing to do with that crate.
```
error[E0433]: failed to resolve: use of undeclared crate or module `group`
  --> C:\Users\danki\.cargo\registry\src\github.com-1ecc6299db9ec823\cglue-gen-0.2.4\src\trait_groups.rs:84:9
   |
84 |         group::parse_braces(input).ok();
   |         ^^^^^ use of undeclared crate or module `group`
```
The culprit seems to be this:
```
error[E0603]: module `group` is private
   --> C:\Users\danki\.cargo\registry\src\github.com-1ecc6299db9ec823\cglue-gen-0.2.4\src\func.rs:5:11
    |
5   | use syn::{group::parse_braces, parse::*, punctuated::Punctuated, token::Comma, Type, *};
    |           ^^^^^ private module
    |
note: the module `group` is defined here
   --> C:\Users\danki\.cargo\registry\src\github.com-1ecc6299db9ec823\syn-1.0.98\src\lib.rs:304:1
    |
304 | mod group;
    | ^^^^^^^^^^
```

**Comment by h33p** [comment]
Right, well, this is fun

**Comment by emesare** [comment]
[Here is the commit](https://github.com/dtolnay/syn/commit/0000e6e911e456c82d90e4bf5937b4a4edaf643f) from the crate `syn` that changed the visibility to private. A quick and dirty solution would be to pin the version of `syn` to 1.0.97 in the manifest file for `cglue-gen`.

**Comment by h33p** [comment]
Fixed it in https://github.com/h33p/cglue/commit/3bd3955aa12313b273c585f8f217b3947ca24fcc.
